package zpp_nape.util;
import nape.callbacks.CbEvent;
import nape.callbacks.InteractionType;
import nape.callbacks.ListenerType;
import nape.callbacks.PreFlag;
import nape.dynamics.ArbiterType;
import nape.geom.Winding;
import nape.phys.BodyType;
import nape.phys.GravMassMode;
import nape.phys.InertiaMode;
import nape.phys.MassMode;
import nape.shape.ShapeType;
import nape.shape.ValidationResult;
import nape.space.Broadphase;
import zpp_nape.space.Broadphase;
#if nape_swc@:keep #end
class ZPP_Flags{
    public static var internal:Bool=false;
    
    public static inline var id_ImmState_ACCEPT=1;
    public static inline var id_ImmState_IGNORE=2;
    public static inline var id_ImmState_ALWAYS=4;
    public static inline var id_GravMassMode_DEFAULT=0;
    public static inline var id_GravMassMode_FIXED=1;
    public static inline var id_GravMassMode_SCALED=2;
    public static inline var id_InertiaMode_DEFAULT=0;
    public static inline var id_InertiaMode_FIXED=1;
    public static inline var id_MassMode_DEFAULT=0;
    public static inline var id_MassMode_FIXED=1;
    public static inline var id_BodyType_STATIC=1;
    public static inline var id_BodyType_DYNAMIC=2;
    public static inline var id_BodyType_KINEMATIC=3;
    public static inline var id_ListenerType_BODY=0;
    public static inline var id_PreFlag_ACCEPT=1;
    public static inline var id_ListenerType_CONSTRAINT=1;
    public static inline var id_PreFlag_IGNORE=2;
    public static inline var id_ListenerType_INTERACTION=2;
    public static inline var id_PreFlag_ACCEPT_ONCE=3;
    public static inline var id_ListenerType_PRE=3;
    public static inline var id_PreFlag_IGNORE_ONCE=4;
    public static inline var id_CbEvent_BEGIN=0;
    public static inline var id_InteractionType_COLLISION=1;
    public static inline var id_CbEvent_ONGOING=6;
    public static inline var id_InteractionType_SENSOR=2;
    public static inline var id_CbEvent_END=1;
    public static inline var id_InteractionType_FLUID=4;
    public static inline var id_CbEvent_WAKE=2;
    public static inline var id_InteractionType_ANY=7;
    public static inline var id_CbEvent_SLEEP=3;
    public static inline var id_CbEvent_BREAK=4;
    public static inline var id_CbEvent_PRE=5;
    public static inline var id_Winding_UNDEFINED=0;
    public static inline var id_Winding_CLOCKWISE=1;
    public static inline var id_Winding_ANTICLOCKWISE=2;
    public static inline var id_ValidationResult_VALID=0;
    public static inline var id_ValidationResult_DEGENERATE=1;
    public static inline var id_ValidationResult_CONCAVE=2;
    public static inline var id_ValidationResult_SELF_INTERSECTING=3;
    public static inline var id_ShapeType_CIRCLE=0;
    public static inline var id_ShapeType_POLYGON=1;
    public static inline var id_Broadphase_DYNAMIC_AABB_TREE=0;
    public static inline var id_Broadphase_SWEEP_AND_PRUNE=1;
    public static inline var id_ArbiterType_COLLISION=1;
    public static inline var id_ArbiterType_SENSOR=2;
    public static inline var id_ArbiterType_FLUID=4;
    
    public static var GravMassMode_DEFAULT:GravMassMode;
    public static var GravMassMode_FIXED:GravMassMode;
    public static var GravMassMode_SCALED:GravMassMode;
    public static var InertiaMode_DEFAULT:InertiaMode;
    public static var InertiaMode_FIXED:InertiaMode;
    public static var MassMode_DEFAULT:MassMode;
    public static var MassMode_FIXED:MassMode;
    public static var BodyType_STATIC:BodyType;
    public static var BodyType_DYNAMIC:BodyType;
    public static var BodyType_KINEMATIC:BodyType;
    public static var ListenerType_BODY:ListenerType;
    public static var PreFlag_ACCEPT:PreFlag;
    public static var ListenerType_CONSTRAINT:ListenerType;
    public static var PreFlag_IGNORE:PreFlag;
    public static var ListenerType_INTERACTION:ListenerType;
    public static var PreFlag_ACCEPT_ONCE:PreFlag;
    public static var ListenerType_PRE:ListenerType;
    public static var PreFlag_IGNORE_ONCE:PreFlag;
    public static var CbEvent_BEGIN:CbEvent;
    public static var InteractionType_COLLISION:InteractionType;
    public static var CbEvent_ONGOING:CbEvent;
    public static var InteractionType_SENSOR:InteractionType;
    public static var CbEvent_END:CbEvent;
    public static var InteractionType_FLUID:InteractionType;
    public static var CbEvent_WAKE:CbEvent;
    public static var InteractionType_ANY:InteractionType;
    public static var CbEvent_SLEEP:CbEvent;
    public static var CbEvent_BREAK:CbEvent;
    public static var CbEvent_PRE:CbEvent;
    public static var Winding_UNDEFINED:Winding;
    public static var Winding_CLOCKWISE:Winding;
    public static var Winding_ANTICLOCKWISE:Winding;
    public static var ValidationResult_VALID:ValidationResult;
    public static var ValidationResult_DEGENERATE:ValidationResult;
    public static var ValidationResult_CONCAVE:ValidationResult;
    public static var ValidationResult_SELF_INTERSECTING:ValidationResult;
    public static var ShapeType_CIRCLE:ShapeType;
    public static var ShapeType_POLYGON:ShapeType;
    public static var Broadphase_DYNAMIC_AABB_TREE:Broadphase;
    public static var Broadphase_SWEEP_AND_PRUNE:Broadphase;
    public static var ArbiterType_COLLISION:ArbiterType;
    public static var ArbiterType_SENSOR:ArbiterType;
    public static var ArbiterType_FLUID:ArbiterType;
}
